---
title: "langevin"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{langevin}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(npmlangevin)
set.seed(5108)
```

```{r}
sim<- simulate(
  nt = 500,
  nping = 400,
  boundary_sharpness = 1,
  boundary_limit = 0.9,
  pred_loc_delta = 0.5,
  ping_tau = 0.1 * c(1, 1),
  gamma = 0.1,
  cv_code = 1,
  cv_pars = c(0.2, 0.3, 1),
  loc_class_probs = c(
    G = 0.1,
    `3` = 0.2,
    `2` = 0.2,
    `1` = 0.2,
    `0` = 0.2,
    A = 0.1,
    B = 0
  )
)
```

```{r}
print(
  with(sim$tmap,{
    tmap_arrange(
      pred_field + track + pings,
      pred_util + track + pings,
      nrow = 2
    )
  })
)
```

# If we know the true parameters and track can we estimate the utilization distribution?

```{r}
data<- sim$data
para<- sim$para

para$w<- 0 * sim$field$w
para$true_coord<- sf::st_coordinates(sim$track)
data$pings$coords<- sf::st_coordinates(sim$pings)

data$field_neighbours<- find_nearest_four(
  sim$track,
  sim$nn_graph
)

map<- list(
  boundary_x = as.factor(
    rep(NA, length(para$boundary_x))
  ),
  boundary_y = as.factor(
    rep(NA, length(para$boundary_y))
  ),
  working_boundary_sharpness = as.factor(
    rep(NA, length(para$working_boundary_sharpness))
  ),
  working_cv_pars = as.factor(
    rep(NA, length(para$working_cv_pars))
  ),
  true_coord = as.factor(
    matrix(NA, nrow = nrow(para$true_coord), ncol = ncol(para$true_coord))
  ),
  # log_gamma = as.factor(
  #   rep(NA, length(para$log_gamma))
  # ),
  working_ping_cov_pars = as.factor(
    rep(NA, length(para$working_ping_cov_pars))
  )
)
obj<- TMB::MakeADFun(
  data = data,
  para = para,
  map = map,
  random = c("w", "true_coord"),
  DLL = "npmlangevin_TMB"
)
opt<- nlminb(obj$par, obj$fn, obj$gr)
sdr<- TMB::sdreport(obj, opt$par)

pred<- st_sf(
  data.frame(
    w = as.list(sdr, "Est", report = TRUE)$pw,
    se = as.list(sdr, "Std", report = TRUE)$pw,
    sim$pred_locs
  )
)
pred<- split(pred, pred$v)
pred<- lapply(
  pred,
  function(x) {
    x<- st_as_stars(x[c("w", "se")])
    x<- st_sfc2xy(x)
    return( x )
  }
)
pred<- do.call(c, c(pred, list(along = "v")))
st_dimensions(pred)$v$values<- c("gg", "dxdx", "dydy")
names(st_dimensions(pred))[1:2]<- c("x", "y")
attr(st_dimensions(pred), "raster")$dimensions<- c("x", "y")

pred_field_tm<- tm_shape(pred["w"]) +
  tm_raster(
    style = "cont",
    midpoint = 0,
    interpolate = TRUE,
    # palette = "viridis"
    palette = "PRGn"
  ) +
  tm_facets(nrow = 1, ncol = 3, free.scales = FALSE) +
  tm_layout(legend.outside = FALSE)

pred_util<- exp(pred["w", , , "gg"])
pred_util<- pred_util / sum(pred_util[["w"]])
pred_util_tm<- tm_shape(pred_util) +
  tm_raster(
    style = "cont",
    interpolate = TRUE,
    palette = "Greens"
  )

print(
  tmap_arrange(
    pred_field_tm + sim$tmap$track,
    pred_util_tm + sim$tmap$track,
    nrow = 2
  )
)
```




# If we know the true track can we estimate the parameters and utilization distribution?

```{r}
data<- sim$data
para<- sim$para

para$w<-  sim$field$w
para$true_coord<- sf::st_coordinates(sim$track)
data$pings$coords<- sf::st_coordinates(sim$pings)

data$field_neighbours<- find_nearest_four(
  sim$track,
  sim$nn_graph
)

map<- list(
  boundary_x = as.factor(
    rep(NA, length(para$boundary_x))
  ),
  boundary_y = as.factor(
    rep(NA, length(para$boundary_y))
  ),
  working_boundary_sharpness = as.factor(
    rep(NA, length(para$working_boundary_sharpness))
  ),
  working_cv_pars = as.factor(
    c(1, 2, NA)
  ),
  true_coord = as.factor(
    matrix(NA, nrow = nrow(para$true_coord), ncol = ncol(para$true_coord))
  )
)
obj<- TMB::MakeADFun(
  data = data,
  para = para,
  map = map,
  random = c("w", "true_coord"),
  DLL = "npmlangevin_TMB"
)
opt<- nlminb(obj$par, obj$fn, obj$gr)
sdr<- TMB::sdreport(obj, opt$par)

pred<- st_sf(
  data.frame(
    w = as.list(sdr, "Est", report = TRUE)$pw,
    se = as.list(sdr, "Std", report = TRUE)$pw,
    sim$pred_locs
  )
)
pred<- split(pred, pred$v)
pred<- lapply(
  pred,
  function(x) {
    x<- st_as_stars(x[c("w", "se")])
    x<- st_sfc2xy(x)
    return( x )
  }
)
pred<- do.call(c, c(pred, list(along = "v")))
st_dimensions(pred)$v$values<- c("gg", "dxdx", "dydy")
names(st_dimensions(pred))[1:2]<- c("x", "y")
attr(st_dimensions(pred), "raster")$dimensions<- c("x", "y")

pred_field_tm<- tm_shape(pred["w"]) +
  tm_raster(
    style = "cont",
    midpoint = 0,
    interpolate = TRUE,
    # palette = "viridis"
    palette = "PRGn"
  ) +
  tm_facets(nrow = 1, ncol = 3, free.scales = FALSE) +
  tm_layout(legend.outside = FALSE)

pred_util<- exp(pred["w", , , "gg"])
pred_util<- pred_util / sum(pred_util[["w"]])
pred_util_tm<- tm_shape(pred_util) +
  tm_raster(
    style = "cont",
    interpolate = TRUE,
    palette = "Greens"
  )

print(
  tmap_arrange(
    pred_field_tm + sim$tmap$track,
    pred_util_tm + sim$tmap$track,
    nrow = 2
  )
)
```





# If we know the observation pings and track neighbours can we estimate the parameters, true track, and utilization distribution?

```{r}
data<- sim$data
para<- sim$para

para$w<- 0 * sim$field$w
para$true_coord<- sf::st_coordinates(sim$track)
data$pings$coords<- sf::st_coordinates(sim$pings)

data$field_neighbours<- lapply(
  find_nearest_four(
    sim$track,
    sim$nn_graph
  ),
  `+`,
  -1
)

map<- list(
  boundary_x = as.factor(
    rep(NA, length(para$boundary_x))
  ),
  boundary_y = as.factor(
    rep(NA, length(para$boundary_y))
  ),
  working_boundary_sharpness = as.factor(
    rep(NA, length(para$working_boundary_sharpness))
  ),
  working_cv_pars = as.factor(
    c(1, 2, NA)
  )
)
obj<- TMB::MakeADFun(
  data = data,
  para = para,
  map = map,
  random = c("w", "true_coord"),
  DLL = "npmlangevin_TMB"
)
opt<- nlminb(obj$par, obj$fn, obj$gr)
sdr<- TMB::sdreport(obj, opt$par)

pred<- st_sf(
  data.frame(
    w = as.list(sdr, "Est", report = TRUE)$pw,
    se = as.list(sdr, "Std", report = TRUE)$pw,
    sim$pred_locs
  )
)
pred<- split(pred, pred$v)
pred<- lapply(
  pred,
  function(x) {
    x<- st_as_stars(x[c("w", "se")])
    x<- st_sfc2xy(x)
    return( x )
  }
)
pred<- do.call(c, c(pred, list(along = "v")))
st_dimensions(pred)$v$values<- c("gg", "dxdx", "dydy")
names(st_dimensions(pred))[1:2]<- c("x", "y")
attr(st_dimensions(pred), "raster")$dimensions<- c("x", "y")

pred_field_tm<- tm_shape(pred["w"]) +
  tm_raster(
    style = "cont",
    midpoint = 0,
    interpolate = TRUE,
    # palette = "viridis"
    palette = "PRGn"
  ) +
  tm_facets(nrow = 1, ncol = 3, free.scales = FALSE) +
  tm_layout(legend.outside = FALSE)

pred_util<- exp(pred["w", , , "gg"])
pred_util<- pred_util / sum(pred_util[["w"]])
pred_util_tm<- tm_shape(pred_util) +
  tm_raster(
    style = "cont",
    interpolate = TRUE,
    palette = "Greens"
  )

print(
  tmap_arrange(
    pred_field_tm + sim$tmap$track,
    pred_util_tm + sim$tmap$track,
    nrow = 2
  )
)
```