---
title: "langevin_simulation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{langevin_simulation}
  %\VignetteEnging{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(npmlangevin)
```

```{r}
xlim<- c(-2, 2)
ylim<- c(-2, 2)
boundary_sharpness<- 2.5
boundary_limit<- 0.8

cv_code<- 1
cv_pars<- c(2, 0.5, 6.5)
pred_loc_delta<- 0.25
pred_loc_v<- 1:3

nt<- 500
nping<- 40
gamma<- 0.08

ping_tau<- 0.1 * c(1, 1)
ping_cor<- 0.3
```

```{r}
class_string<- c("G", "3", "2", "1", "0", "A", "B")
loc_class_K<- data.frame(
  q = factor(
    c("G", "3", "2", "1", "0", "A", "B"),
    ordered = TRUE,
    levels = c("G", "3", "2", "1", "0", "A", "B")
  ),
  x = c(0.1, 1, 1.54, 3.72, 13.51, 23.9, 44.22),
  y = c(0.1, 1, 1.29, 2.55, 14.99, 22.0, 32.53)
)
loc_class_probs<- c(
  "G" = 0.026,
  "3" = 0.040,
  "2" = 0.035,
  "1" = 0.020,
  "0" = 0.065,
  "A" = 0.126,
  "B" = 0.688
)
```

```{r}
g<- make_nn_graph(
  x = xlim,
  y = ylim,
  cv_pars = cv_pars,
  cv_code = cv_code
)

pred_locs<- st_as_sf(
  expand.grid(
    x = seq(min(xlim), max(xlim), by = pred_loc_delta),
    y = seq(min(ylim), max(ylim), by = pred_loc_delta),
    v = pred_loc_v
  ),
  coords = c("x", "y")
)
pwg<- make_pred_graph(
  pred_locs,
  g
)

true_time<- sort(cumsum(runif(nt, 0, 2)))
track_idx<- sort(sample(seq(nt), nping, replace = TRUE))
loc_class<- sample(loc_class_K$q, nping, replace = TRUE, prob = loc_class_probs)
```

```{r sim}
simobj<- MakeADFun(
  data = list(
    model = "langevin_diffusion",
    cv_code = cv_code,
    g = list(
      st_get_dimension_values(g$stars, "x"),
      st_get_dimension_values(g$stars, "y"),
      lapply(lapply(g$graph, `[[`, 1), `+`, -1),
      lapply(lapply(g$graph, `[[`, 2), `+`, -1)
    ),
    pwg = pred_graph_to_cpp(pwg),
    true_time = true_time,
    pings = list(
      coords = matrix(0, nrow = nping, ncol = 2),
      loc_class = as.numeric(loc_class) - 1,
      track_idx = track_idx - 1,
      K = as.matrix(loc_class_K[, c("x", "y")])
    )
  ),
  para = list(
    boundary_x = boundary_limit * xlim,
    boundary_y = boundary_limit * ylim,
    working_boundary_sharpness = log(boundary_sharpness),
    working_cv_pars = log(cv_pars),
    w = g$stars$w,
    pw = numeric(length(pwg$v)),
    true_coord = matrix(0, nrow = nt, ncol = 2),
    log_gamma = log(gamma),
    working_ping_cov_pars = c(
      log(ping_tau[[1]]),
      qlogis(0.5 + 0.5 * ping_cor),
      log(ping_tau[[2]])
    )
  ),
  map = list(
    boundary_x = as.factor(c(NA, NA)),
    boundary_y = as.factor(c(NA, NA)),
    working_boundary_sharpness = as.factor(NA)
  ),
  random = c("w", "pw", "true_coord"),
  DLL = "npmlangevin_TMB"
)
sim<- simobj$simulate()

g$stars$w<- sim$w
simtrack<- st_as_sf(as.data.frame(sim$true_coord), coords = c(1, 2)) |> st_combine() |> st_cast("LINESTRING")

pred<- st_sf(
  data.frame(
    w = sim$pw,
    pred_locs
  )
)
pred<- split(pred, pred$v)
pred<- lapply(
  pred,
  function(x) {
    x<- st_as_stars(x["w"])
    x<- st_sfc2xy(x)
    return( x )
  }
)
pred<- do.call(c, c(pred, list(along = "v")))
st_dimensions(pred)$v$values<- c("gg", "dxdx", "dydy")
names(st_dimensions(pred))[1:2]<- c("x", "y")
attr(st_dimensions(pred), "raster")$dimensions<- c("x", "y")

```

```{r plot_sim}
sim_rasters<- tm_shape(g$stars["w"]) +
  tm_raster(
    style = "cont",
    midpoint = 0,
    interpolate = FALSE,
    # palette = "viridis"
    palette = "PRGn"
  ) +
  tm_facets(nrow = 1, ncol = 3, free.scales = FALSE) +
  tm_layout(legend.outside = FALSE)

pred_rasters<- tm_shape(pred["w"]) +
  tm_raster(
    style = "cont",
    midpoint = 0,
    interpolate = TRUE,
    # palette = "viridis"
    palette = "PRGn"
  ) +
  tm_facets(nrow = 1, ncol = 3, free.scales = FALSE) +
  tm_layout(legend.outside = FALSE)


sim_util<- exp(g$stars["w", , , "gg"])
sim_util<- sim_util / sum(sim_util[["w"]])
sim_util_tm<- tm_shape(sim_util) +
  tm_raster(
    style = "cont",
    interpolate = FALSE,
    palette = "Greens"
  )

pred_util<- exp(pred["w", , , "gg"])
pred_util<- pred_util / sum(pred_util[["w"]])
pred_util_tm<- tm_shape(pred_util) +
  tm_raster(
    style = "cont",
    interpolate = TRUE,
    palette = "Greens"
  )

sim_track<- tm_shape(simtrack) + tm_lines(col = "black")
```

```{r, fig.height = 10, fig.width = 8, out.width = '100%', out.height = '100%'}
# tmap_arrange(sim_rasters + sim_track, sim_util_tm + sim_track, nrow = 2)
tmap_arrange(pred_rasters + sim_track, pred_util_tm + sim_track, nrow = 2)
```


```{r}
do_a_simulation<- function(seed) {
  if( !missing(seed) ) {
    set.seed(seed)
  } else {}

  class_string<- c("G", "3", "2", "1", "0", "A", "B")
  loc_class_K<- data.frame(
    q = factor(
      c("G", "3", "2", "1", "0", "A", "B"),
      ordered = TRUE,
      levels = c("G", "3", "2", "1", "0", "A", "B")
    ),
    x = c(0.1, 1, 1.54, 3.72, 13.51, 23.9, 44.22),
    y = c(0.1, 1, 1.29, 2.55, 14.99, 22.0, 32.53)
  )
  loc_class_probs<- c(
    "G" = 0.026,
    "3" = 0.040,
    "2" = 0.035,
    "1" = 0.020,
    "0" = 0.065,
    "A" = 0.126,
    "B" = 0.688
  )

  g<- make_nn_graph(
    x = xlim,
    y = ylim,
    cv_pars = cv_pars,
    cv_code = cv_code
  )

  pred_locs<- st_as_sf(
    expand.grid(
      x = seq(min(xlim), max(xlim), by = pred_loc_delta),
      y = seq(min(ylim), max(ylim), by = pred_loc_delta),
      v = pred_loc_v
    ),
    coords = c("x", "y")
  )
  pwg<- make_pred_graph(
    pred_locs,
    g
  )

  true_time<- sort(cumsum(runif(nt, 0, 2)))
  track_idx<- sort(sample(seq(nt), nping, replace = TRUE))
  loc_class<- sample(loc_class_K$q, nping, replace = TRUE, prob = loc_class_probs)

  simobj<- MakeADFun(
    data = list(
      model = "langevin_diffusion",
      cv_code = cv_code,
      g = list(
        st_get_dimension_values(g$stars, "x"),
        st_get_dimension_values(g$stars, "y"),
        lapply(lapply(g$graph, `[[`, 1), `+`, -1),
        lapply(lapply(g$graph, `[[`, 2), `+`, -1)
      ),
      pwg = pred_graph_to_cpp(pwg),
      true_time = true_time,
      pings = list(
        coords = matrix(0, nrow = nping, ncol = 2),
        loc_class = as.numeric(loc_class) - 1,
        track_idx = track_idx - 1,
        K = as.matrix(loc_class_K[, c("x", "y")])
      )
    ),
    para = list(
      boundary_x = boundary_limit * xlim,
      boundary_y = boundary_limit * ylim,
      working_boundary_sharpness = log(boundary_sharpness),
      working_cv_pars = log(cv_pars),
      w = g$stars$w,
      pw = numeric(length(pwg$v)),
      true_coord = matrix(0, nrow = nt, ncol = 2),
      log_gamma = log(gamma),
      working_ping_cov_pars = c(
        log(ping_tau[[1]]),
        qlogis(0.5 + 0.5 * ping_cor),
        log(ping_tau[[2]])
      )
    ),
    map = list(
      boundary_x = as.factor(c(NA, NA)),
      boundary_y = as.factor(c(NA, NA)),
      working_boundary_sharpness = as.factor(NA)
    ),
    random = c("w", "pw", "true_coord"),
    DLL = "npmlangevin_TMB"
  )
  sim<- simobj$simulate()

  g$stars$w<- sim$w
  sim_track<- st_as_sf(as.data.frame(sim$true_coord), coords = c(1, 2)) |> st_combine() |> st_cast("LINESTRING")

  pred<- st_sf(
    data.frame(
      w = sim$pw,
      pred_locs
    )
  )
  pred<- split(pred, pred$v)
  pred<- lapply(
    pred,
    function(x) {
      x<- st_as_stars(x["w"])
      x<- st_sfc2xy(x)
      return( x )
    }
  )
  pred<- do.call(c, c(pred, list(along = "v")))
  st_dimensions(pred)$v$values<- c("gg", "dxdx", "dydy")
  names(st_dimensions(pred))[1:2]<- c("x", "y")
  attr(st_dimensions(pred), "raster")$dimensions<- c("x", "y")

  pred_util<- exp(pred["w", , , "gg"])
  pred_util<- pred_util / sum(pred_util[["w"]])

  return(list(seed = seed, sim_w = g$stars, pred = pred, pred_util = pred_util, sim_track = sim_track))
}
```

```{r sim-all, message=FALSE, warning=FALSE}
xlim<- c(-2, 2)
ylim<- c(-2, 2)
boundary_sharpness<- 2.5
boundary_limit<- 0.8

cv_code<- 1
cv_pars<- c(2, 0.5, 6.5)
pred_loc_delta<- 0.25
pred_loc_v<- 1:3

nt<- 500
nping<- 40
gamma<- 0.08

ping_tau<- 0.1 * c(1, 1)
ping_cor<- 0.3


sims<- lapply(seq(50), do_a_simulation)
```

```{r}
plot_sim<- function(x, with_track = TRUE) {
  st_crs(x$pred)<- st_crs(4326)
  pred_rasters<- tm_shape(x$pred["w"], projection = st_crs(4326)) +
    tm_raster(
      style = "cont",
      midpoint = 0,
      interpolate = TRUE,
      # palette = "viridis"
      palette = "PRGn"
    ) +
    tm_facets(nrow = 1, ncol = 3, free.scales = FALSE) +
    tm_layout(legend.outside = FALSE)

  st_crs(x$pred_util)<- st_crs(4326)
  pred_util_tm<- tm_shape(x$pred_util, projection = st_crs(4326)) +
    tm_raster(
      style = "cont",
      interpolate = TRUE,
      palette = "Greens"
    )

  st_crs(x$sim_track)<- st_crs(4326)
  sim_track<- tm_shape(x$sim_track, projection = st_crs(4326)) + tm_lines(col = "black")

  if( with_track ) {
    return(
      tmap_arrange(
        pred_rasters + sim_track,
        pred_util_tm + sim_track,
        nrow = 2
      )
    )
  } else {
    return(
      tmap_arrange(
        pred_rasters,
        pred_util_tm,
        nrow = 2
      )
    )
  }
}
```

```{r plot-all, fig.height = 10, fig.width = 8, out.width = '100%', out.height = '100%', fig.keep = 'all'}
for( i in seq_along(sims) ) {
  print(i)
  print(plot_sim(sims[[i]], FALSE))
  print(plot_sim(sims[[i]], TRUE))
  print("")
}
```