---
title: "starve-langevin"
output: rmarkdown::html_vignette
vignette: >
    %\VignetteIndexEntry{starve-langevin}
    %\VignetteEnging{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
# knitr::opts_chunk$set(
#     collapse = TRUE,
#     comment = "#>"
# )
```

```{r setup}
library(npmlangevin)
# set.seed(5108)
```

```{r simulate}
sim<- simulate(
    nt = 500,
    nping = 400,
    boundary_sharpness = 0,
    boundary_limit = 1,
    pred_loc_delta = 0.5,
    ping_tau = 0.1 * c(1, 1),
    gamma = 0.05,
    cv_code = 1,
    cv_pars = c(0.15, 0.3, 1),
    # loc_class_probs = c(
    #     G = 0.1,
    #     `3` = 0.1,
    #     `2` = 0.2,
    #     `1` = 0.2,
    #     `0` = 0.2,
    #     A = 0.2,
    #     B = 0.0
    # )
    loc_class_probs = c(
        G = 0.4,
        `3` = 0.3,
        `2` = 0.3,
        `1` = 0.0,
        `0` = 0.0,
        A = 0.0,
        B = 0.0
    )
)
```

```{r}
print(
    with(
        sim$tmap,
        {
            tmap_arrange(
                pred_field + track + pings,
                pred_util + track + pings,
                nrow = 2
            )
        }
    )
)
```


# Fit data

```{r}
filtered_locations<- fit_rw(
  locations = sim$pings
)
estimated_field<- fit_utilization_distribution(
  filtered_locations = filtered_locations,
  cv_code = 1,
  max.edge = 0.3,
  cutoff = 0.05
)
```

# Plot results

## Filtered track

```{r}
filtered_tm<- tm_shape(st_cast(st_combine(filtered_locations$track), "LINESTRING")) +
  tm_lines(col = "red")
filtered_tm + sim$tmap$track + sim$tmap$pings
```


## Utilization Distribution

```{r}
tm_shape(sim$pred_field["w"][, , , 1:3]) + 
    tm_raster(
      style = "cont",
      midpoint = 0,
      interpolate = TRUE,
      palette = "PRGn"
    ) +
  tm_shape(estimated_field$mesh_predictions) +
    tm_dots(
      col = c("g", "dx", "dy"),
      size = 0.2,
      style = "cont",
      palette = "PRGn"
    ) +
  tm_facets(nrow = 1, ncol = 3, free.scales = TRUE) +
  tm_layout(legend.outside = FALSE)
```

## Utilization Distribution and Track

```{r}
sim$tmap$track +  
  tm_shape(estimated_field$mesh_predictions) +
    tm_dots(
      col = c("g"),
      size = 0.2,
      style = "cont",
      midpoint = NA,
      palette = "Greens"
    )
```


# Get predictions

```{r}
bbox<- st_bbox(sim$field)
r<- raster(
  xmn = bbox["xmin"],
  xmx = bbox["xmax"],
  ymn = bbox["ymin"],
  ymx = bbox["ymax"],
  nrow = 40,
  ncol = 40,
  crs = NULL
)
pred_locations<- sf::st_as_sf(raster::rasterToPoints(r, spatial = TRUE))
pred_locations<- predict_utilization_distribution(
  pred_locations,
  estimated_field,
  k = 1
)
pred_r<- stars::st_rasterize(
  pred_locations,
  template = stars::st_as_stars(r)
)
pred_r$util<- exp(pred_r$g)
pred_r$util<- pred_r$util / sum(pred_r$util)
```

```{r}
tm_shape(pred_r["util"], master = TRUE) +
    tm_raster(
      style = "cont",
      interpolate = FALSE,
      palette = "Greens"
    ) + 
  sim$tmap$track
```

```{r}

```